apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    traefik.ingress.kubernetes.io/service.server-scheme: https
    traefik.ingress.kubernetes.io/service.servers-transport.insecureskipverify: "true"
spec:
  ingressClassName: traefik
  rules:
  - host: argocd.lab
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 8443

