apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: cluster-argo
servers: 1
agents: 2
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
registries:
  use:
    - k3d-reg:5000
options:
  k3d:
    disableLoadbalancer: false
