apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: go-server
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: engineering-dev
        url: https://kubernetes.default.svc
      # - cluster: engineering-prod
      #   url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{.cluster}}-go-server'
    spec:
      project: default
      source:
        repoURL: https://natanbs.github.io/go-server/Packages
        targetRevision: "*"
        chart: go-server
        helm:
          values: |
            controller:
              service:
                type: ClusterIP
      destination:
        server: '{{.url}}'
        namespace: default
