apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-server
  namespace: argocd
spec:
  project: default
  destination:
    namespace: app-ns
    name: in-cluster   #update cluster name if its different
  source:
    repoURL: https://natanbs.github.io/go-server/Packages
    targetRevision: "*"
    chart: go-server
    helm:
      values: |
        controller:
          service:
            type: ClusterIP    
