apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: go-server
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: go-server
    spec:
      project: default
      source:
        repoURL: https://natanbs.github.io/go-server/Packages
        targetRevision: "*"
        chart: go-server
      destination:
        server: '{{.url}}'
        namespace: app-ns
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
